package application.backend.web;

import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/player")
public class VideoPlayerController {

    @GetMapping(produces = MediaType.TEXT_HTML_VALUE)
    @ResponseBody
    public String renderPlayer(@RequestParam(value = "v", required = true) String videoId) {
        String safeId = videoId.replaceAll("[^a-zA-Z0-9_-]", "");
        return "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "  <meta name=\"referrer\" content=\"strict-origin-when-cross-origin\">\n"
                + "  <title>Video Lecture Player</title>\n"
                + "  <style>\n"
                + "    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
                + "    html, body {\n"
                + "      width: 100%;\n"
                + "      height: 100%;\n"
                + "      background-color: #0b0f19;\n"
                + "      overflow: hidden;\n"
                + "      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;\n"
                + "      display: flex;\n"
                + "      flex-direction: column;\n"
                + "      user-select: none;\n"
                + "    }\n"
                + "    #video-wrapper {\n"
                + "      position: relative;\n"
                + "      flex: 1;\n"
                + "      width: 100%;\n"
                + "      background: #000000;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "    #player, iframe {\n"
                + "      position: absolute;\n"
                + "      top: 0; left: 0;\n"
                + "      width: 100%;\n"
                + "      height: 100%;\n"
                + "      border: 0;\n"
                + "    }\n"
                + "    #controls {\n"
                + "      height: 44px;\n"
                + "      min-height: 44px;\n"
                + "      background: #111827;\n"
                + "      border-top: 1px solid #1f2937;\n"
                + "      display: flex;\n"
                + "      align-items: center;\n"
                + "      padding: 0 10px;\n"
                + "      gap: 8px;\n"
                + "      color: #f3f4f6;\n"
                + "      z-index: 10;\n"
                + "    }\n"
                + "    .btn {\n"
                + "      background: #1f2937;\n"
                + "      border: 1px solid #374151;\n"
                + "      color: #f3f4f6;\n"
                + "      padding: 5px 9px;\n"
                + "      border-radius: 6px;\n"
                + "      font-size: 12px;\n"
                + "      font-weight: 600;\n"
                + "      cursor: pointer;\n"
                + "      display: inline-flex;\n"
                + "      align-items: center;\n"
                + "      justify-content: center;\n"
                + "      transition: background 0.15s, border-color 0.15s, transform 0.08s;\n"
                + "      white-space: nowrap;\n"
                + "    }\n"
                + "    .btn:hover {\n"
                + "      background: #374151;\n"
                + "      border-color: #4b5563;\n"
                + "    }\n"
                + "    .btn:active {\n"
                + "      transform: scale(0.96);\n"
                + "    }\n"
                + "    .btn-primary {\n"
                + "      background: #6366f1;\n"
                + "      border-color: #818cf8;\n"
                + "      color: #ffffff;\n"
                + "    }\n"
                + "    .btn-primary:hover {\n"
                + "      background: #4f46e5;\n"
                + "    }\n"
                + "    .btn-skip {\n"
                + "      background: #1e293b;\n"
                + "      border-color: #334155;\n"
                + "      color: #38bdf8;\n"
                + "      font-weight: 700;\n"
                + "    }\n"
                + "    .btn-skip:hover {\n"
                + "      background: #0f172a;\n"
                + "      border-color: #38bdf8;\n"
                + "    }\n"
                + "    #time-box {\n"
                + "      font-size: 11px;\n"
                + "      font-variant-numeric: tabular-nums;\n"
                + "      color: #9ca3af;\n"
                + "      min-width: 75px;\n"
                + "      text-align: center;\n"
                + "      white-space: nowrap;\n"
                + "    }\n"
                + "    #seek-container {\n"
                + "      flex: 1;\n"
                + "      position: relative;\n"
                + "      height: 24px;\n"
                + "      display: flex;\n"
                + "      align-items: center;\n"
                + "      cursor: pointer;\n"
                + "      margin: 0 4px;\n"
                + "    }\n"
                + "    #seek-rail {\n"
                + "      position: relative;\n"
                + "      width: 100%;\n"
                + "      height: 6px;\n"
                + "      background: #374151;\n"
                + "      border-radius: 3px;\n"
                + "      overflow: visible;\n"
                + "      transition: height 0.12s;\n"
                + "    }\n"
                + "    #seek-container:hover #seek-rail {\n"
                + "      height: 8px;\n"
                + "    }\n"
                + "    #seek-buffered {\n"
                + "      position: absolute;\n"
                + "      top: 0; left: 0;\n"
                + "      height: 100%;\n"
                + "      background: #4b5563;\n"
                + "      border-radius: 3px;\n"
                + "      width: 0%;\n"
                + "    }\n"
                + "    #seek-progress {\n"
                + "      position: absolute;\n"
                + "      top: 0; left: 0;\n"
                + "      height: 100%;\n"
                + "      background: linear-gradient(90deg, #6366f1, #a855f7);\n"
                + "      border-radius: 3px;\n"
                + "      width: 0%;\n"
                + "    }\n"
                + "    #seek-thumb {\n"
                + "      position: absolute;\n"
                + "      top: 50%; right: -6px;\n"
                + "      transform: translateY(-50%);\n"
                + "      width: 12px; height: 12px;\n"
                + "      border-radius: 50%;\n"
                + "      background: #ffffff;\n"
                + "      box-shadow: 0 0 5px rgba(99,102,241,0.8);\n"
                + "      transition: transform 0.1s;\n"
                + "    }\n"
                + "    #seek-container:hover #seek-thumb {\n"
                + "      transform: translateY(-50%) scale(1.3);\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <div id=\"video-wrapper\">\n"
                + "    <div id=\"player\"></div>\n"
                + "  </div>\n"
                + "  <div id=\"controls\">\n"
                + "    <button id=\"playBtn\" class=\"btn btn-primary\" onclick=\"togglePlay()\">▶ Play</button>\n"
                + "    <button class=\"btn btn-skip\" onclick=\"seekBy(-10)\" title=\"Rewind 10 seconds\">⏪ -10s</button>\n"
                + "    <button class=\"btn btn-skip\" onclick=\"seekBy(10)\" title=\"Skip forward 10 seconds\">+10s ⏩</button>\n"
                + "    <div id=\"time-box\"><span id=\"curTime\">0:00</span> / <span id=\"durTime\">0:00</span></div>\n"
                + "    <div id=\"seek-container\">\n"
                + "      <div id=\"seek-rail\">\n"
                + "        <div id=\"seek-buffered\"></div>\n"
                + "        <div id=\"seek-progress\"><div id=\"seek-thumb\"></div></div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <button id=\"rateBtn\" class=\"btn\" onclick=\"cycleRate()\" title=\"Playback Speed\">1.0x</button>\n"
                + "  </div>\n"
                + "  <script>\n"
                + "    var videoId = '" + safeId + "';\n"
                + "    var player = null;\n"
                + "    var isDragging = false;\n"
                + "    var rates = [1.0, 1.25, 1.5, 1.75, 2.0];\n"
                + "    var rateIdx = 0;\n"
                + "\n"
                + "    var seekContainer = document.getElementById('seek-container');\n"
                + "    var seekRail = document.getElementById('seek-rail');\n"
                + "    var seekProgress = document.getElementById('seek-progress');\n"
                + "    var seekBuffered = document.getElementById('seek-buffered');\n"
                + "    var curTimeLabel = document.getElementById('curTime');\n"
                + "    var durTimeLabel = document.getElementById('durTime');\n"
                + "    var playBtn = document.getElementById('playBtn');\n"
                + "    var rateBtn = document.getElementById('rateBtn');\n"
                + "\n"
                + "    function formatTime(sec) {\n"
                + "      var s = Math.floor(sec) || 0;\n"
                + "      var m = Math.floor(s / 60);\n"
                + "      s = s % 60;\n"
                + "      var h = Math.floor(m / 60);\n"
                + "      m = m % 60;\n"
                + "      var sStr = s < 10 ? '0' + s : '' + s;\n"
                + "      if (h > 0) {\n"
                + "        var mStr = m < 10 ? '0' + m : '' + m;\n"
                + "        return h + ':' + mStr + ':' + sStr;\n"
                + "      }\n"
                + "      return m + ':' + sStr;\n"
                + "    }\n"
                + "\n"
                + "    function onYouTubeIframeAPIReady() {\n"
                + "      player = new YT.Player('player', {\n"
                + "        width: '100%',\n"
                + "        height: '100%',\n"
                + "        videoId: videoId,\n"
                + "        host: 'https://www.youtube-nocookie.com',\n"
                + "        playerVars: {\n"
                + "          'autoplay': 1,\n"
                + "          'playsinline': 1,\n"
                + "          'rel': 0,\n"
                + "          'controls': 1,\n"
                + "          'modestbranding': 1,\n"
                + "          'enablejsapi': 1,\n"
                + "          'origin': window.location.origin\n"
                + "        },\n"
                + "        events: {\n"
                + "          'onReady': onPlayerReady,\n"
                + "          'onStateChange': onPlayerStateChange\n"
                + "        }\n"
                + "      });\n"
                + "    }\n"
                + "\n"
                + "    function onPlayerReady(event) {\n"
                + "      try {\n"
                + "        if (typeof player.setPlaybackQuality === 'function') {\n"
                + "          player.setPlaybackQuality('hd720');\n"
                + "        }\n"
                + "      } catch(e) {}\n"
                + "      try {\n"
                + "        player.playVideo();\n"
                + "      } catch(e) {}\n"
                + "    }\n"
                + "\n"
                + "    function onPlayerStateChange(event) {\n"
                + "      if (event.data === 1) {\n"
                + "        playBtn.innerText = '⏸ Pause';\n"
                + "        playBtn.classList.remove('btn-primary');\n"
                + "        try {\n"
                + "          if (typeof player.setPlaybackQuality === 'function') {\n"
                + "            player.setPlaybackQuality('hd720');\n"
                + "          }\n"
                + "        } catch(e) {}\n"
                + "      } else {\n"
                + "        playBtn.innerText = '▶ Play';\n"
                + "        playBtn.classList.add('btn-primary');\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    window.togglePlay = function() {\n"
                + "      if (!player) return;\n"
                + "      if (typeof player.getPlayerState === 'function') {\n"
                + "        if (player.getPlayerState() === 1) {\n"
                + "          player.pauseVideo();\n"
                + "        } else {\n"
                + "          player.playVideo();\n"
                + "        }\n"
                + "      }\n"
                + "    };\n"
                + "\n"
                + "    window.seekBy = function(offset) {\n"
                + "      if (!player || typeof player.getCurrentTime !== 'function') return;\n"
                + "      var cur = player.getCurrentTime() || 0;\n"
                + "      var dur = player.getDuration() || 0;\n"
                + "      var target = Math.max(0, Math.min(dur, cur + offset));\n"
                + "      player.seekTo(target, true);\n"
                + "      updateTimeline(target, dur);\n"
                + "    };\n"
                + "\n"
                + "    window.cycleRate = function() {\n"
                + "      if (!player || typeof player.setPlaybackRate !== 'function') return;\n"
                + "      rateIdx = (rateIdx + 1) % rates.length;\n"
                + "      var r = rates[rateIdx];\n"
                + "      player.setPlaybackRate(r);\n"
                + "      rateBtn.innerText = r + 'x';\n"
                + "    };\n"
                + "\n"
                + "    function seekToClientX(clientX) {\n"
                + "      if (!player || typeof player.getDuration !== 'function') return;\n"
                + "      var rect = seekRail.getBoundingClientRect();\n"
                + "      var x = clientX - rect.left;\n"
                + "      var fraction = Math.max(0, Math.min(1, x / rect.width));\n"
                + "      var dur = player.getDuration() || 0;\n"
                + "      if (dur > 0) {\n"
                + "        var target = fraction * dur;\n"
                + "        player.seekTo(target, true);\n"
                + "        updateTimeline(target, dur);\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    seekContainer.addEventListener('mousedown', function(e) {\n"
                + "      isDragging = true;\n"
                + "      seekToClientX(e.clientX);\n"
                + "    });\n"
                + "\n"
                + "    document.addEventListener('mousemove', function(e) {\n"
                + "      if (isDragging) {\n"
                + "        seekToClientX(e.clientX);\n"
                + "      }\n"
                + "    });\n"
                + "\n"
                + "    document.addEventListener('mouseup', function(e) {\n"
                + "      if (isDragging) {\n"
                + "        seekToClientX(e.clientX);\n"
                + "        isDragging = false;\n"
                + "      }\n"
                + "    });\n"
                + "\n"
                + "    function updateTimeline(cur, dur) {\n"
                + "      curTimeLabel.innerText = formatTime(cur);\n"
                + "      durTimeLabel.innerText = formatTime(dur);\n"
                + "      if (dur > 0) {\n"
                + "        var pct = (cur / dur) * 100;\n"
                + "        seekProgress.style.width = pct + '%';\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    setInterval(function() {\n"
                + "      if (!isDragging && player && typeof player.getCurrentTime === 'function') {\n"
                + "        var cur = player.getCurrentTime() || 0;\n"
                + "        var dur = player.getDuration() || 0;\n"
                + "        if (typeof player.getVideoLoadedFraction === 'function') {\n"
                + "          seekBuffered.style.width = (player.getVideoLoadedFraction() * 100) + '%';\n"
                + "        }\n"
                + "        updateTimeline(cur, dur);\n"
                + "      }\n"
                + "    }, 350);\n"
                + "\n"
                + "    document.addEventListener('keydown', function(e) {\n"
                + "      if (e.key === 'ArrowLeft') { seekBy(-10); e.preventDefault(); }\n"
                + "      else if (e.key === 'ArrowRight') { seekBy(10); e.preventDefault(); }\n"
                + "      else if (e.key === ' ' || e.key === 'k') { togglePlay(); e.preventDefault(); }\n"
                + "    });\n"
                + "\n"
                + "    setTimeout(function() {\n"
                + "      if (!player) {\n"
                + "        var wrapper = document.getElementById('video-wrapper');\n"
                + "        wrapper.innerHTML = '<iframe id=\"player\" src=\"https://www.youtube-nocookie.com/embed/' + videoId + '?autoplay=1&playsinline=1&rel=0&enablejsapi=1&origin=' + encodeURIComponent(window.location.origin) + '\" referrerpolicy=\"strict-origin-when-cross-origin\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>';\n"
                + "      }\n"
                + "    }, 3500);\n"
                + "\n"
                + "    var tag = document.createElement('script');\n"
                + "    tag.src = 'https://www.youtube.com/iframe_api';\n"
                + "    var firstScriptTag = document.getElementsByTagName('script')[0];\n"
                + "    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);\n"
                + "  </script>\n"
                + "</body>\n"
                + "</html>";
    }
}
