package application.backend.web;

import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/player")
public class VideoPlayerController {

    @GetMapping(produces = MediaType.TEXT_HTML_VALUE)
    @ResponseBody
    public String renderPlayer(@RequestParam(value = "v", required = true) String videoId) {
        String safeId = videoId.replaceAll("[^a-zA-Z0-9_-]", "");
        return "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "  <meta charset=\"utf-8\">\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "  <meta name=\"referrer\" content=\"strict-origin-when-cross-origin\">\n"
                + "  <title>Video Lecture Player</title>\n"
                + "  <style>\n"
                + "    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
                + "    html, body {\n"
                + "      width: 100%;\n"
                + "      height: 100%;\n"
                + "      background-color: #0b0f19;\n"
                + "      overflow: hidden;\n"
                + "      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;\n"
                + "      display: flex;\n"
                + "      flex-direction: column;\n"
                + "      user-select: none;\n"
                + "    }\n"
                + "    #video-wrapper {\n"
                + "      position: relative;\n"
                + "      flex: 1;\n"
                + "      width: 100%;\n"
                + "      background: #000000;\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "    #player, iframe {\n"
                + "      position: absolute;\n"
                + "      top: 0; left: 0;\n"
                + "      width: 100%;\n"
                + "      height: 100%;\n"
                + "      border: 0;\n"
                + "    }\n"
                + "    #controls {\n"
                + "      height: 48px;\n"
                + "      min-height: 48px;\n"
                + "      background: #0f172a;\n"
                + "      border-top: 1px solid #1e293b;\n"
                + "      display: flex;\n"
                + "      align-items: center;\n"
                + "      padding: 0 14px;\n"
                + "      gap: 10px;\n"
                + "      color: #f8fafc;\n"
                + "      z-index: 10;\n"
                + "    }\n"
                + "    .btn {\n"
                + "      background: #1e293b;\n"
                + "      border: 1px solid #334155;\n"
                + "      color: #f1f5f9;\n"
                + "      padding: 6px 12px;\n"
                + "      border-radius: 7px;\n"
                + "      font-size: 12px;\n"
                + "      font-weight: 700;\n"
                + "      cursor: pointer;\n"
                + "      display: inline-flex;\n"
                + "      align-items: center;\n"
                + "      justify-content: center;\n"
                + "      transition: background 0.12s, border-color 0.12s, transform 0.08s;\n"
                + "      white-space: nowrap;\n"
                + "    }\n"
                + "    .btn:hover {\n"
                + "      background: #334155;\n"
                + "      border-color: #475569;\n"
                + "    }\n"
                + "    .btn:active {\n"
                + "      transform: scale(0.96);\n"
                + "    }\n"
                + "    .btn-primary {\n"
                + "      background: #4f46e5;\n"
                + "      border-color: #6366f1;\n"
                + "      color: #ffffff;\n"
                + "    }\n"
                + "    .btn-primary:hover {\n"
                + "      background: #4338ca;\n"
                + "    }\n"
                + "    .btn-skip {\n"
                + "      background: #1e1b4b;\n"
                + "      border-color: #4338ca;\n"
                + "      color: #a5b4fc;\n"
                + "      font-weight: 700;\n"
                + "    }\n"
                + "    .btn-skip:hover {\n"
                + "      background: #312e81;\n"
                + "      border-color: #6366f1;\n"
                + "      color: #ffffff;\n"
                + "    }\n"
                + "    #time-box {\n"
                + "      font-size: 12px;\n"
                + "      font-variant-numeric: tabular-nums;\n"
                + "      color: #cbd5e1;\n"
                + "      min-width: 90px;\n"
                + "      text-align: center;\n"
                + "      white-space: nowrap;\n"
                + "      font-weight: 600;\n"
                + "    }\n"
                + "    #seek-container {\n"
                + "      flex: 1;\n"
                + "      position: relative;\n"
                + "      height: 28px;\n"
                + "      display: flex;\n"
                + "      align-items: center;\n"
                + "      cursor: pointer;\n"
                + "      margin: 0 6px;\n"
                + "    }\n"
                + "    #seek-rail {\n"
                + "      position: relative;\n"
                + "      width: 100%;\n"
                + "      height: 6px;\n"
                + "      background: #334155;\n"
                + "      border-radius: 4px;\n"
                + "      overflow: visible;\n"
                + "      transition: height 0.12s;\n"
                + "    }\n"
                + "    #seek-container:hover #seek-rail {\n"
                + "      height: 8px;\n"
                + "    }\n"
                + "    #seek-buffered {\n"
                + "      position: absolute;\n"
                + "      top: 0; left: 0;\n"
                + "      height: 100%;\n"
                + "      background: #475569;\n"
                + "      border-radius: 4px;\n"
                + "      width: 0%;\n"
                + "    }\n"
                + "    #seek-progress {\n"
                + "      position: absolute;\n"
                + "      top: 0; left: 0;\n"
                + "      height: 100%;\n"
                + "      background: linear-gradient(90deg, #6366f1, #a855f7);\n"
                + "      border-radius: 4px;\n"
                + "      width: 0%;\n"
                + "    }\n"
                + "    #seek-thumb {\n"
                + "      position: absolute;\n"
                + "      top: 50%; right: -7px;\n"
                + "      transform: translateY(-50%);\n"
                + "      width: 14px; height: 14px;\n"
                + "      border-radius: 50%;\n"
                + "      background: #ffffff;\n"
                + "      box-shadow: 0 0 6px rgba(99,102,241,0.9);\n"
                + "      transition: transform 0.1s;\n"
                + "    }\n"
                + "    #seek-container:hover #seek-thumb {\n"
                + "      transform: translateY(-50%) scale(1.25);\n"
                + "    }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body>\n"
                + "  <div id=\"video-wrapper\">\n"
                + "    <div id=\"player\"></div>\n"
                + "  </div>\n"
                + "  <div id=\"controls\">\n"
                + "    <button id=\"playBtn\" class=\"btn btn-primary\" onclick=\"togglePlay()\">▶ Play</button>\n"
                + "    <button class=\"btn btn-skip\" onclick=\"seekBy(-10)\" title=\"Rewind 10s\">⏪ -10s</button>\n"
                + "    <button class=\"btn btn-skip\" onclick=\"seekBy(10)\" title=\"Fast-forward 10s\">+10s ⏩</button>\n"
                + "    <div id=\"time-box\"><span id=\"curTime\">0:00</span> / <span id=\"durTime\">0:00</span></div>\n"
                + "    <div id=\"seek-container\">\n"
                + "      <div id=\"seek-rail\">\n"
                + "        <div id=\"seek-buffered\"></div>\n"
                + "        <div id=\"seek-progress\"><div id=\"seek-thumb\"></div></div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <button id=\"rateBtn\" class=\"btn\" onclick=\"cycleRate()\" title=\"Speed\">1.0x</button>\n"
                + "  </div>\n"
                + "  <script>\n"
                + "    var videoId = '" + safeId + "';\n"
                + "    var player = null;\n"
                + "    var isDragging = false;\n"
                + "    var isSeeking = false;\n"
                + "    var seekTargetTime = 0;\n"
                + "    var seekLockTimer = null;\n"
                + "    var rates = [1.0, 1.25, 1.5, 1.75, 2.0];\n"
                + "    var rateIdx = 0;\n"
                + "    var localCurrentTime = 0;\n"
                + "    var totalDuration = 0;\n"
                + "\n"
                + "    var seekContainer = document.getElementById('seek-container');\n"
                + "    var seekRail = document.getElementById('seek-rail');\n"
                + "    var seekProgress = document.getElementById('seek-progress');\n"
                + "    var seekBuffered = document.getElementById('seek-buffered');\n"
                + "    var curTimeLabel = document.getElementById('curTime');\n"
                + "    var durTimeLabel = document.getElementById('durTime');\n"
                + "    var playBtn = document.getElementById('playBtn');\n"
                + "    var rateBtn = document.getElementById('rateBtn');\n"
                + "\n"
                + "    function formatTime(sec) {\n"
                + "      var s = Math.max(0, Math.floor(sec)) || 0;\n"
                + "      var m = Math.floor(s / 60);\n"
                + "      s = s % 60;\n"
                + "      var h = Math.floor(m / 60);\n"
                + "      m = m % 60;\n"
                + "      var sStr = s < 10 ? '0' + s : '' + s;\n"
                + "      if (h > 0) {\n"
                + "        var mStr = m < 10 ? '0' + m : '' + m;\n"
                + "        return h + ':' + mStr + ':' + sStr;\n"
                + "      }\n"
                + "      return m + ':' + sStr;\n"
                + "    }\n"
                + "\n"
                + "    function onYouTubeIframeAPIReady() {\n"
                + "      player = new YT.Player('player', {\n"
                + "        width: '100%',\n"
                + "        height: '100%',\n"
                + "        videoId: videoId,\n"
                + "        host: 'https://www.youtube.com',\n"
                + "        playerVars: {\n"
                + "          'autoplay': 1,\n"
                + "          'playsinline': 1,\n"
                + "          'rel': 0,\n"
                + "          'controls': 0,\n"
                + "          'modestbranding': 1,\n"
                + "          'enablejsapi': 1,\n"
                + "          'origin': window.location.origin\n"
                + "        },\n"
                + "        events: {\n"
                + "          'onReady': onPlayerReady,\n"
                + "          'onStateChange': onPlayerStateChange\n"
                + "        }\n"
                + "      });\n"
                + "    }\n"
                + "\n"
                + "    function onPlayerReady(event) {\n"
                + "      try {\n"
                + "        if (typeof player.getDuration === 'function') {\n"
                + "          totalDuration = player.getDuration() || 0;\n"
                + "          if (totalDuration > 0) durTimeLabel.innerText = formatTime(totalDuration);\n"
                + "        }\n"
                + "        player.playVideo();\n"
                + "      } catch(e) {}\n"
                + "    }\n"
                + "\n"
                + "    function onPlayerStateChange(event) {\n"
                + "      if (event.data === 1) {\n"
                + "        playBtn.innerText = '⏸ Pause';\n"
                + "        playBtn.classList.remove('btn-primary');\n"
                + "        if (typeof player.getDuration === 'function') {\n"
                + "          var d = player.getDuration();\n"
                + "          if (d > 0) {\n"
                + "            totalDuration = d;\n"
                + "            durTimeLabel.innerText = formatTime(d);\n"
                + "          }\n"
                + "        }\n"
                + "      } else {\n"
                + "        playBtn.innerText = '▶ Play';\n"
                + "        playBtn.classList.add('btn-primary');\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    window.togglePlay = function() {\n"
                + "      if (!player) return;\n"
                + "      try {\n"
                + "        if (typeof player.getPlayerState === 'function') {\n"
                + "          if (player.getPlayerState() === 1) {\n"
                + "            player.pauseVideo();\n"
                + "          } else {\n"
                + "            player.playVideo();\n"
                + "          }\n"
                + "        }\n"
                + "      } catch(e) {}\n"
                + "    };\n"
                + "\n"
                + "    function sendSeek(targetSec) {\n"
                + "      targetSec = Math.max(0, targetSec);\n"
                + "      if (totalDuration > 0) targetSec = Math.min(totalDuration, targetSec);\n"
                + "\n"
                + "      var sought = false;\n"
                + "      if (player && typeof player.seekTo === 'function') {\n"
                + "        try {\n"
                + "          player.seekTo(targetSec, true);\n"
                + "          sought = true;\n"
                + "        } catch(e) {}\n"
                + "      }\n"
                + "\n"
                + "      if (!sought) {\n"
                + "        var ifr = document.querySelector('iframe');\n"
                + "        if (ifr && ifr.contentWindow) {\n"
                + "          try {\n"
                + "            ifr.contentWindow.postMessage(JSON.stringify({\n"
                + "              event: 'command',\n"
                + "              func: 'seekTo',\n"
                + "              args: [targetSec, true]\n"
                + "            }), '*');\n"
                + "          } catch(e) {}\n"
                + "        }\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    window.seekBy = function(offset) {\n"
                + "      var dur = totalDuration;\n"
                + "      if (player && typeof player.getDuration === 'function') {\n"
                + "        var realDur = player.getDuration();\n"
                + "        if (realDur > 0) { dur = realDur; totalDuration = realDur; }\n"
                + "      }\n"
                + "\n"
                + "      var baseTime = localCurrentTime;\n"
                + "      if (!isSeeking && player && typeof player.getCurrentTime === 'function') {\n"
                + "        var realCur = player.getCurrentTime();\n"
                + "        if (typeof realCur === 'number' && !isNaN(realCur) && realCur >= 0) {\n"
                + "          baseTime = realCur;\n"
                + "        }\n"
                + "      }\n"
                + "\n"
                + "      var target = Math.max(0, baseTime + offset);\n"
                + "      if (dur > 0) target = Math.min(dur, target);\n"
                + "\n"
                + "      localCurrentTime = target;\n"
                + "      seekTargetTime = target;\n"
                + "      isSeeking = true;\n"
                + "      if (seekLockTimer) clearTimeout(seekLockTimer);\n"
                + "      seekLockTimer = setTimeout(function() {\n"
                + "        isSeeking = false;\n"
                + "      }, 1500);\n"
                + "\n"
                + "      updateTimeline(target, dur);\n"
                + "      sendSeek(target);\n"
                + "    };\n"
                + "\n"
                + "    window.cycleRate = function() {\n"
                + "      if (!player || typeof player.setPlaybackRate !== 'function') return;\n"
                + "      rateIdx = (rateIdx + 1) % rates.length;\n"
                + "      var r = rates[rateIdx];\n"
                + "      player.setPlaybackRate(r);\n"
                + "      rateBtn.innerText = r + 'x';\n"
                + "    };\n"
                + "\n"
                + "    function updateTimeline(cur, dur) {\n"
                + "      curTimeLabel.innerText = formatTime(cur);\n"
                + "      if (dur > 0) {\n"
                + "        durTimeLabel.innerText = formatTime(dur);\n"
                + "        var pct = Math.max(0, Math.min(100, (cur / dur) * 100));\n"
                + "        seekProgress.style.width = pct + '%';\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    function getFraction(clientX) {\n"
                + "      var rect = seekRail.getBoundingClientRect();\n"
                + "      var x = clientX - rect.left;\n"
                + "      return Math.max(0, Math.min(1, x / rect.width));\n"
                + "    }\n"
                + "\n"
                + "    seekContainer.addEventListener('mousedown', function(e) {\n"
                + "      isDragging = true;\n"
                + "      var frac = getFraction(e.clientX);\n"
                + "      var dur = totalDuration || (player && typeof player.getDuration === 'function' ? player.getDuration() : 0) || 0;\n"
                + "      if (dur > 0) {\n"
                + "        var target = frac * dur;\n"
                + "        localCurrentTime = target;\n"
                + "        seekTargetTime = target;\n"
                + "        updateTimeline(target, dur);\n"
                + "      }\n"
                + "    });\n"
                + "\n"
                + "    document.addEventListener('mousemove', function(e) {\n"
                + "      if (isDragging) {\n"
                + "        var frac = getFraction(e.clientX);\n"
                + "        var dur = totalDuration || (player && typeof player.getDuration === 'function' ? player.getDuration() : 0) || 0;\n"
                + "        if (dur > 0) {\n"
                + "          var target = frac * dur;\n"
                + "          localCurrentTime = target;\n"
                + "          seekTargetTime = target;\n"
                + "          updateTimeline(target, dur);\n"
                + "        }\n"
                + "      }\n"
                + "    });\n"
                + "\n"
                + "    document.addEventListener('mouseup', function(e) {\n"
                + "      if (isDragging) {\n"
                + "        isDragging = false;\n"
                + "        var frac = getFraction(e.clientX);\n"
                + "        var dur = totalDuration || (player && typeof player.getDuration === 'function' ? player.getDuration() : 0) || 0;\n"
                + "        if (dur > 0) {\n"
                + "          var target = frac * dur;\n"
                + "          localCurrentTime = target;\n"
                + "          seekTargetTime = target;\n"
                + "          isSeeking = true;\n"
                + "          if (seekLockTimer) clearTimeout(seekLockTimer);\n"
                + "          seekLockTimer = setTimeout(function() {\n"
                + "            isSeeking = false;\n"
                + "          }, 1500);\n"
                + "          updateTimeline(target, dur);\n"
                + "          sendSeek(target);\n"
                + "        }\n"
                + "      }\n"
                + "    });\n"
                + "\n"
                + "    setInterval(function() {\n"
                + "      if (!isDragging && player) {\n"
                + "        try {\n"
                + "          if (typeof player.getDuration === 'function') {\n"
                + "            var d = player.getDuration();\n"
                + "            if (d > 0 && totalDuration !== d) {\n"
                + "              totalDuration = d;\n"
                + "              durTimeLabel.innerText = formatTime(d);\n"
                + "            }\n"
                + "          }\n"
                + "          if (typeof player.getVideoLoadedFraction === 'function') {\n"
                + "            var loaded = player.getVideoLoadedFraction();\n"
                + "            if (typeof loaded === 'number' && !isNaN(loaded)) {\n"
                + "              seekBuffered.style.width = (loaded * 100) + '%';\n"
                + "            }\n"
                + "          }\n"
                + "          if (typeof player.getCurrentTime === 'function') {\n"
                + "            var c = player.getCurrentTime();\n"
                + "            if (typeof c === 'number' && !isNaN(c)) {\n"
                + "              if (isSeeking) {\n"
                + "                if (Math.abs(c - seekTargetTime) < 1.0) {\n"
                + "                  isSeeking = false;\n"
                + "                  if (seekLockTimer) clearTimeout(seekLockTimer);\n"
                + "                  localCurrentTime = c;\n"
                + "                  updateTimeline(c, totalDuration);\n"
                + "                }\n"
                + "              } else {\n"
                + "                localCurrentTime = c;\n"
                + "                updateTimeline(c, totalDuration);\n"
                + "              }\n"
                + "            }\n"
                + "          }\n"
                + "        } catch(e) {}\n"
                + "      }\n"
                + "    }, 250);\n"
                + "\n"
                + "    document.addEventListener('keydown', function(e) {\n"
                + "      if (e.key === 'ArrowLeft') { seekBy(-10); e.preventDefault(); }\n"
                + "      else if (e.key === 'ArrowRight') { seekBy(10); e.preventDefault(); }\n"
                + "      else if (e.key === ' ' || e.key === 'k') { togglePlay(); e.preventDefault(); }\n"
                + "    });\n"
                + "\n"
                + "    var tag = document.createElement('script');\n"
                + "    tag.src = 'https://www.youtube.com/iframe_api';\n"
                + "    var firstScriptTag = document.getElementsByTagName('script')[0];\n"
                + "    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);\n"
                + "  </script>\n"
                + "</body>\n"
                + "</html>";
    }
}
